const Rocket = require("../src/models/rockets");

export const mockRocketsNew = [
  new Rocket({
    rocketId: "0",
    rocketType: "A",
    mission: "x123",
    launchSpeed: 500,
    currentSpeed: 500,
    lastSpeedIncrease: null,
    lastSpeedDecrease: null,
    lastUpdatedMission: "2022-06-04T11:15:55.558Z",
    lastMessageSpeedIncrease: null,
    lastMessageSpeedDecrease: null,
    lastMessageMission: 1,
    exploded: false,
    explodedReason: "",
  }),
  new Rocket({
    rocketId: "1",
    rocketType: "B",
    mission: "x124",
    launchSpeed: 500,
    currentSpeed: 500,
    lastSpeedIncrease: null,
    lastSpeedDecrease: null,
    lastUpdatedMission: "2022-06-04T12:15:55.558Z",
    lastMessageSpeedIncrease: null,
    lastMessageSpeedDecrease: null,
    lastMessageMission: 1,
    exploded: false,
    explodedReason: "",
  }),
  new Rocket({
    rocketId: "2",
    rocketType: "A",
    mission: "y123",
    launchSpeed: 500,
    currentSpeed: 500,
    lastSpeedIncrease: null,
    lastSpeedDecrease: null,
    lastUpdatedMission: "2022-06-04T11:16:55.558Z",
    lastMessageSpeedIncrease: null,
    lastMessageSpeedDecrease: null,
    lastMessageMission: 1,
    exploded: false,
    explodedReason: "",
  }),
  new Rocket({
    rocketId: "4",
    rocketType: "F",
    mission: "y124",
    launchSpeed: 600,
    currentSpeed: 600,
    lastSpeedIncrease: null,
    lastSpeedDecrease: null,
    lastUpdatedMission: "2022-06-04T11:15:55.558Z",
    lastMessageSpeedIncrease: null,
    lastMessageSpeedDecrease: null,
    lastMessageMission: 1,
    exploded: false,
    explodedReason: "",
  }),
  new Rocket({
    rocketId: "5",
    rocketType: "A",
    mission: "xy123",
    launchSpeed: 100,
    currentSpeed: 100,
    lastSpeedIncrease: null,
    lastSpeedDecrease: null,
    lastUpdatedMission: "2022-06-04T11:15:55.558Z",
    lastMessageSpeedIncrease: null,
    lastMessageSpeedDecrease: null,
    lastMessageMission: 1,
    exploded: false,
    explodedReason: "",
  }),
  new Rocket({
    rocketId: "6",
    rocketType: "ABC",
    mission: "xyz123",
    launchSpeed: 1000,
    currentSpeed: 1000,
    lastSpeedIncrease: null,
    lastSpeedDecrease: null,
    lastUpdatedMission: "2022-06-04T10:15:55.558Z",
    lastMessageSpeedIncrease: null,
    lastMessageSpeedDecrease: null,
    lastMessageMission: 1,
    exploded: false,
    explodedReason: "",
  }),
];
// for all the tests I never made
export const mockRocketsUpdated = [];
export const mockLaunchMessages = [];
export const mockSpeedIncreaseMessages = [];
export const mockSpeedDecreaseMessages = [];
export const mockMissionChangeMessages = [];
export const mockExplodedMessages = [];
